services:
  web:
    image: ghcr.io/akramboussanni/personal:main
    volumes:
      - ./content-data:/data/content
      - ./public/uploads:/app/public/uploads
    environment:
      NODE_ENV: production
      PORT: 3000
      CONTENT_DIR: /data/content
    restart: unless-stopped

networks:
  web:
    external: true
